### ISSUE TITLE
Does Arthur enrich the data? 

### ISSUE THREAD

**Issue by Julianbaozi** [chaoss/grimoirelab-kingarthur#110]
Does Arthur only fetch the raw data? Is there a way to enrich data in multiprocess?

And also can I start different workers on one machine?

**Comment by valeriocos** [comment]
Hi @Julianbaozi 

> Does Arthur only fetch the raw data?
yes Arthur fetches only raw data.

> Is there a way to enrich data in multiprocess?
You can use micro-mordred or mordred as commented at https://github.com/chaoss/grimoirelab-sirmordred/issues/462#issuecomment-622957274

> And also can I start different workers on one machine?
Yes

Would you mind opening an issue in https://github.com/chaoss/grimoirelab and describe your use case. We can try to figure out how to help you, thanks!

**Comment by valeriocos** [comment]
Replaced by https://github.com/chaoss/grimoirelab/issues/325
