### ISSUE TITLE
Documentation: Configuration file?

### ISSUE THREAD

**Issue by olblak** [chaoss/grimoirelab-kingarthur#19]
Hi 
I see that we can run an arthur daemon with a configuration file but I can't find an example (or documentation) of this one.
Does it exist?

**Comment by mafesan** [comment]
Hi @olblak,
Indeed, `arthur` daemon can run using an `ini` confiiguration file, here is an example:

```
[arthur]
cache_path = /tmp/.arthur/cache
debug = True
log_path = /tmp/logs/arthurd
no_cache = True
sync_mode = True
[connection]
host = 127.0.0.1
port= 8080
[elasticsearch]
es_index = http://localhost:9200/items
[redis]
database = redis://localhost/8
```

We'll update the documentation with this information very soon, thank you for your feedback!

**Comment by olblak** [comment]
Thanks for this

**Comment by jjmerchante** [comment]
This information was added in this PR: https://github.com/chaoss/grimoirelab-kingarthur/pull/24
