### ISSUE TITLE
Tasks are not re-triggered

### ISSUE THREAD

**Issue by olblak** [chaoss/grimoirelab-kingarthur#30]
Is it the role of arthur to update tasks on a regular basics like hourly?
When used with mordred I noticed that I have to flush the redis database and restart arthur/mordred if I want to have new job in redis

**Comment by sduenas** [comment]
Unless tasks fail, they're re-scheduled as soon as they finish. The `delay` parameter allows to configure how long a task will be sleeping/delayed before it gets re-scheduled again. I don't think this is your problem, though.

@acs have you found the same problem?

**Comment by acs** [comment]
> @acs have you found the same problem?

Now, it has worked correctly in my testing. Tasks are created one time, and after that, they are rescheduled and rexecuted using the **delay** as time interval between executions.

**Comment by olblak** [comment]
Thank you for the feedback so I guess something is broken in my setup
