### ISSUE TITLE
command to output larger data-set

### ISSUE THREAD

**Issue by FredaPinto** [chaoss/grimoirelab-kingarthur#66]
Hi Team,

Thanks for constantly showing support.
Here I am with yet another issue that is I was able to start and follow all steps to generate till task.
I need some help to understand how to check all records generated from task in elasticsearch?
i am trying to fetch node js repository data for further analysis and i could create tasks.json and see everything but not sure how to see the entire data set loaded ?

Regards

**Comment by valeriocos** [comment]
Hi @FredaPinto ,
If your question is about how to inspect the content of an index, you can use kibana. If you are using the default docker-compose it should be available at localhost:5601. Please have a look at the gif below to see how to create an index pattern from the indexes in your ElasticSearch and discover their data.

![Peek 16-07-2019 08-38](https://user-images.githubusercontent.com/6515067/61271671-8a1b5400-a7a5-11e9-8e9b-79dac53fe3db.gif)

I hope this helps

**Comment by sduenas** [comment]
What method are you doing to store data? By default, Arthur writes data in a queue in Redis. Although, there's also the possibility to write data to a ElasticSearch index.

If you followed the README, that's what you are doing with the next command:
```
arthurd -g -d redis://localhost/8 --es-index http://localhost:9200/items --log-path /tmp/logs/arthud --no-archive
```
Items will be written to the index `items` in `http://localhost:9200`. You can check if everything was written there following the steps that Valerio described above.

**Comment by valeriocos** [comment]
Hi @FredaPinto , any news about this issue? thanks!

**Comment by FredaPinto** [comment]
Hi Valerio,

I will test and let you know today , couldn't check it yesterday.

Regards,
Freda

**Comment by valeriocos** [comment]
thank you for the quick reply Freda

**Comment by FredaPinto** [comment]
Hi Valerio and Santiago,

Thanks for your reply.
I checked as per steps in readme and also tried to create index as per @valeriocos video but i can't see the index name when i try to create it.
The index name should be items but its not detectable from kibana so i am trying to check that if you know something that could help please let me know.

Regards,
Freda

**Comment by sduenas** [comment]
Try to list what indices you have in your ES instance. You can do it with something like:

https://127.0.0.1:9200/_cat/indices

(replace the IP, with the one where you're running Elasaticsearch)

**Comment by FredaPinto** [comment]
Hi Santiago,

I checked this command and got below output:-

green  open .monitoring-kibana-6-2019.07.19 dsOBV9vxRYSJ8-QWcBSxNA 1 0
  165   0   87.1kb   87.1kb
green  open .monitoring-kibana-6-2019.07.18 d7-lW6Y1QO-1aUOxgbdlrg 1 0
 3232   0      1mb      1mb
green  open .kibana_1                       2ZSwBekzT7K5fTkn4eVlwg 1 0
    5   0   29.1kb   29.1kb
yellow open items                           FWjQvvhkREqo7sODUnn3YA 5 1
    0   0    1.2kb    1.2kb
green  open .monitoring-es-6-2019.07.19     MYZTWc83S8qKeZWyM-sg-Q 1 0
 1676  15 1010.3kb 1010.3kb
green  open .monitoring-es-6-2019.07.18     5aTo6nLrRBukIKA2zZLleA 1 0
25919 104   11.2mb   11.2mb

Also i can see items if i see in kibana through index management for
elasticsearch.

Please let me know if any have any suggestions.

The software version im using :-Kibana and elastic (6.6.2).

[image: Screenshot 2019-07-19 at 11.23.30.png]

**Comment by valeriocos** [comment]
Hi Freda, the fix just merged to the master branch (https://github.com/chaoss/grimoirelab-kingarthur/pull/70) should solve your issue. Once you see the data in the `items` index, you can check the total number of docs in it with https://localhost:9200/items/_count?pretty

Let us know how it goes, thanks!

**Comment by FredaPinto** [comment]
Hi Valerio,

It is working ,thanks.
Just that i can only see 5 entries for repository i am fetching that is as
per example arthur.git.
I will investigate more to see if there is something in logs to see if data
is fetched correctly.


Regards,
Freda

**Comment by sduenas** [comment]
Great @FredaPinto,

probably you already analyzed the repository before and you only got the new items. In the example, the repository is stored in `tmp/git/arthur.git/`. You can remove it and run everything again to check what happens.
