### ISSUE TITLE
Moving task scheduling outside of king arthur 

### ISSUE THREAD

**Issue by acs** [chaoss/grimoirelab-kingarthur#73]
Hi,

After one year working with different Big Data platforms I have reached the conclusion that the task scheduling should be done outside arthur. arthur should be a task repository and also the engine for executing the tasks, tracking the execution, stopping it and having stats about the track executions. The real execution is done by the data processing engine. In our case, RQ and the python tasks for collecting the data.

The task scheduling is something totally different from the task execution. For example in Unix systems, the scheduling is done using tools like cron. In our case, for the GrimoireLab platform, there is a python based tool called Airflow (https://airflow.apache.org/) which is the base for the Google Composer service, demoing its maturity.

Airflow could asks arthur to execute the jobs according to different schedules. The scheduling could be defined in Python code, and it has a great web interface to visualize complex scheduling (I am not sure but probably you can also visualize the execution process of the tasks).

My proposal is to use Airflow in GrimoireLab platform for task scheduling, and to simplify arthur cleaning the logic related to scheduling.

**Comment by alpgarcia** [comment]
@acs in that scenario, why do you need Arthur? I guess airflow is able to execute the jobs and there will be options to track them so that each job can inform about its status.

**Comment by acs** [comment]
You need arthur to execute the jobs. The idea is that airflow asks arthur to execute jobs using its REST API. Airflow can not execute jobs in a distributed fashion by itself.

**Comment by acs** [comment]
Thanks for the explanation @sduenas. Yes, I was thinking in scheduling for all GrimoireLab tasks, not just perceval ones. For example, all the scheduling done in mordred. IMHO, if you decide to use a scheduling tool for GrimoireLab, you will need arthur for task registering and execution, which I envision must be the core features of arthur.

Just my 2 cents!
