### ISSUE TITLE
Allow to run again a failed task

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-kingarthur#76]
When a task fails is impossible to reload it. So far, the only way to do that is to delete and add the task again. This is a problem since related information, like jobs history will be lost.

Arthur should provide a method to re-run these tasks, probably updating their configuration parameters.

**Comment by sduenas** [comment]
After talking and thinking about this, we'll keep it as simple as possible. This is to reset the counter and to allow to run the task the same number of times it was configured originally.

**Comment by bhaskardv** [comment]
Any update on the fix.

**Comment by sduenas** [comment]
@bhaskardv I've just merged #101 which adds this feature.
