### ISSUE TITLE
Persistent tasks

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-kingarthur#88]
As the number of repositories to analyze increases in Arthur it starts to make sense to store the tasks in a persistent place. In my opinion, tasks should be stored in **Redis**, taking as an example the way `rq` stores its `Job` objects.

After implementing this, and as a future work, Arthur will be able to read the tasks from the storage system once the service is restarted.

**Comment by valeriocos** [comment]
Why the tasks should be stored in Redis and not using a sqlite DB (as similarly done with the [Perceval archive](https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/archive.py)) ?

**Comment by sduenas** [comment]
Since jobs, results, items are stored using Redis, I think it makes more sense to keep using the same and not adding two different systems for storing related things.
