### ISSUE TITLE
Update depedencies

### ISSUE THREAD

**Issue by valeriocos** [chaoss/grimoirelab-kingarthur#90]
Arthur relies on old dependencies (see below). Since we are putting effort on it, it would be good to update them to reduce the gap with the latest ones available.
```
redis==3.0.0 ---> latest 3.3.11
rq==1.0.0 ---> latest 1.3.1
cheroot==5.8.3 ---> latest 8.2.1
cherrypy>=8.1, <=11.0.0 ---> latest 18.3.0
```

**Comment by sduenas** [comment]
Sounds good but I'm afraid we cannot update to a later version of cherrypy without big changes. Anyway, let's consider it.
