### ISSUE TITLE
Failed tasks on 'create' queue are rescheduled into 'update'

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-kingarthur#93]
When a task fails inside the `create` queue it is re-scheduled into `update` queue. These tasks should be re-scheduled into `create`.

**Comment by mafesan** [comment]
I'm working on this issue.

AFAIK, the method behind this behaviour is in `scheduler.py` script and it is called `_determine_queue`.

After discussing with @sduenas, we agreed on defining a new queue for retries and move those tasks which failed based on the value from the parameter `task.num_failures`. This will be the new behaviour:
* If `task.num_failures` > 0, then the task will be sent to this new retries queue.
* If the task succeded, `task.num_failures`  will be reset to 0.
* Field `task.age` still will be incremented even if the task failed.

**Comment by mafesan** [comment]
I have submitted a PR aiming to solve this issue: https://github.com/chaoss/grimoirelab-kingarthur/pull/107.
